**Author:** Elias Rafael Ruiz-Morales

**Institution:** Wellcome Sanger institute

**July, 2023**

---

## Generate cellphoneDB input files (1) _meta.tsv and (2) _degs.tsv

reference: https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_anndata.ipynb
reference: https://github.com/ventolab/HGDA/blob/main/human/scRNAseq/cellphoneDB/cellphoneDB1_granulosa_preparefiles.ipynb

In [2]:
import numpy as np
import pandas as pd
import scanpy as sc
import anndata
import os
import sys
sys.executable

'/opt/conda/bin/python'

In [53]:
def recoverDEGs(DEGdf, infection, celltype, direction):

    
    ### Up reg
    ###
    if direction=='up':

        #selecting only up regulated genes
        tempUP = DEGdf[DEGdf['logFC'] > 0].copy()
        
        #making new columns
        tempUP['cell_type'] = celltype
        tempUP['cluster'] = celltype + '.' + infection
        tempUP['gene']=list(tempUP.index.values)

        # select significant less restrictive
        tempUP =tempUP[ tempUP.p_val_adj < 0.05]
        tempUP = tempUP[ tempUP.logFC > 0.1]

        
        return(tempUP)


    ### Down reg
    ###
    if direction=='down':
        #selecting only down regulated genes
        tempUP = DEGdf[DEGdf['logFC'] < 0].copy()
        
        #making new columns
        tempUP['cell_type'] = celltype
        tempUP['cluster'] = celltype + '.' + infection
        tempUP['gene']=list(tempUP.index.values)


        # select significant less restrictive
        tempUP =tempUP[ tempUP.p_val_adj < 0.05]
        tempUP = tempUP[ tempUP.logFC < -0.1]
        
        return(tempDwn)

## Prepare INPUT

### (1) Load annadata_ single-cell explants from listeria infection

In [3]:
adata = sc.read('../../data_integration/results/scVI/listeria_singleCell_24h.h5ad')

In [4]:
adata.obs['cell_type'].values.describe()

            counts     freqs
categories
EVT_1          106  0.003438
EVT_2          602  0.019523
Endo_f        5714  0.185309
F             5017  0.162705
F_p            334  0.010832
F_sm            71  0.002303
HBC           7948  0.257759
HBC_p           18  0.000584
PAMM1         2055  0.066645
PV            3441  0.111594
VCT           1575  0.051078
VCT_CCC        536  0.017383
VCT_fusing    2682  0.086979
VCT_p          403  0.013070
iEVT           333  0.010799

In [5]:
adata.obs['stage_perInfection'].values.describe()

            counts     freqs
categories
Lm_24h       17778  0.576553
UI_Lm_24h    13057  0.423447

In [6]:
adata

AnnData object with n_obs × n_vars = 30835 × 36601
    obs: 'sample', 'stage', 'hpi', 'infection', 'percent_mito', 'n_counts', 'sample_barcode', 'assignment_SoC', 'donor_id', 'scrublet_score', 'scrublet_cluster_score', 'zscore', 'bh_pval', 'bonf_pval', 'S_score', 'G2M_score', 'phase', 'n_genes_by_counts', 'total_counts', 'total_counts_hs', 'pct_counts_hs', 'total_counts_tg', 'pct_counts_tg', 'Tg_infected', 'n_genes', '_scvi_batch', '_scvi_labels', '_scvi_local_l_mean', '_scvi_local_l_var', 'leiden_scvi', 'celltype_predictions', 'probabilities', 'scrublet_doublet', 'cell_type_2022', 'cell_type', 'souporcell_MFgenotype', 'MFgenotype', 'cell_type_broad', 'umap_density_Tg_infected', 'stage_perInfection', 'celltype-Stage', 'Tg_intracellular', 'celltype-Intracellular', 'Dev_Stage'
    var: 'gene_ids', 'feature_types', 'mean-0', 'std-0', 'mean-1', 'std-1', 'mean-2', 'std-2', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'Dev_Stage_colors', 'MFgenotype_colors', '_scvi', 'cell_type_2022_colors', 'cell_type_broad_colors', 'cell_type_colors', 'celltype_predictions_colors', 'donor_id_colors', 'hpi_colors', 'hvg', 'infection_colors', 'leiden', 'neighbors', 'sample_colors', 'scrublet_doublet_colors', 'umap', 'umap_density_Tg_infected_params'
    obsm: 'X_scVI_n_latent_20', 'X_scVI_n_latent_30', 'X_scVI_n_latent_40', 'X_umap', '_scvi_extra_categoricals'
    layers: 'raw_counts'
    obsp: 'connectivities', 'distances'

### DO NOT Subset dataset, use full matrix counts from infected manifod!!
This is because we want to predict the cell-cell interactions during infection using the DEG in infection

In [69]:
#Take only the INFECTED counts matrix
cellphoneDB_adata = adata[adata.obs['stage_perInfection']=='Lm_24h'].copy()

/opt/conda/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2487: FutureWarning: The `inplace` parameter in pandas.Categorical.remove_unused_categories is deprecated and will be removed in a future version.
  res = method(*args, **kwargs)

In [70]:
#Take only the UNINFECTED counts matrix
#cellphoneDB_adataUI = adata[adata.obs['stage_perInfection']=='UI_Lm_24h'].copy()

In [71]:
cellphoneDB_adata.obs['cell_type']

Pla_HDBR12330713_AAACCCAAGTAGAGTT       HBC
Pla_HDBR12330713_AAACCCACAATTCTCT         F
Pla_HDBR12330713_AAACCCACAGGCTACC       HBC
Pla_HDBR12330713_AAACCCACATCGTCCT         F
Pla_HDBR12330713_AAACCCAGTACCGCGT       HBC
                                      ...
Pla_HDBR13661572_TTTGTTGAGGTTCATC       HBC
Pla_HDBR13661572_TTTGTTGCAAATTAGG    Endo_f
Pla_HDBR13661572_TTTGTTGCAATAGGGC         F
Pla_HDBR13661572_TTTGTTGGTGCTTATG    Endo_f
Pla_HDBR13661572_TTTGTTGGTGGTAACG     PAMM1
Name: cell_type, Length: 17778, dtype: category
Categories (15, object): ['EVT_1', 'EVT_2', 'Endo_f', 'F', ..., 'VCT_CCC', 'VCT_fusing', 'VCT_p', 'iEVT']

In [72]:
cellphoneDB_adata.obs['donor_id'].values.describe()

            counts     freqs
categories
Hrv135        3964  0.222972
Hrv136        2956  0.166273
Hrv236       10858  0.610755

In [73]:
cellphoneDB_adata

AnnData object with n_obs × n_vars = 17778 × 36601
    obs: 'sample', 'stage', 'hpi', 'infection', 'percent_mito', 'n_counts', 'sample_barcode', 'assignment_SoC', 'donor_id', 'scrublet_score', 'scrublet_cluster_score', 'zscore', 'bh_pval', 'bonf_pval', 'S_score', 'G2M_score', 'phase', 'n_genes_by_counts', 'total_counts', 'total_counts_hs', 'pct_counts_hs', 'total_counts_tg', 'pct_counts_tg', 'Tg_infected', 'n_genes', '_scvi_batch', '_scvi_labels', '_scvi_local_l_mean', '_scvi_local_l_var', 'leiden_scvi', 'celltype_predictions', 'probabilities', 'scrublet_doublet', 'cell_type_2022', 'cell_type', 'souporcell_MFgenotype', 'MFgenotype', 'cell_type_broad', 'umap_density_Tg_infected', 'stage_perInfection', 'celltype-Stage', 'Tg_intracellular', 'celltype-Intracellular', 'Dev_Stage'
    var: 'gene_ids', 'feature_types', 'mean-0', 'std-0', 'mean-1', 'std-1', 'mean-2', 'std-2', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'Dev_Stage_colors', 'MFgenotype_colors', '_scvi', 'cell_type_2022_colors', 'cell_type_broad_colors', 'cell_type_colors', 'celltype_predictions_colors', 'donor_id_colors', 'hpi_colors', 'hvg', 'infection_colors', 'leiden', 'neighbors', 'sample_colors', 'scrublet_doublet_colors', 'umap', 'umap_density_Tg_infected_params'
    obsm: 'X_scVI_n_latent_20', 'X_scVI_n_latent_30', 'X_scVI_n_latent_40', 'X_umap', '_scvi_extra_categoricals'
    layers: 'raw_counts'
    obsp: 'connectivities', 'distances'

In [74]:
cellphoneDB_adata.obs['stage_perInfection'].values.describe()

            counts  freqs
categories
Lm_24h       17778    1.0

### Load *new* cell clusters annotation

In [75]:
### Add cluster subname such that this new name will match with DEG cluster name

#INFECTED
cellphoneDB_adata.obs['cell_type']= cellphoneDB_adata.obs.cell_type.astype('string')+'.'+cellphoneDB_adata.obs.infection.astype('string')

#UI
#cellphoneDB_adataUI.obs['cell_type']= cellphoneDB_adataUI.obs.cell_type.astype('string')+'.'+cellphoneDB_adataUI.obs.stage_perInfection.astype('string')

In [76]:
cellphoneDB_adata.obs['cell_type']

Pla_HDBR12330713_AAACCCAAGTAGAGTT       HBC.Lm
Pla_HDBR12330713_AAACCCACAATTCTCT         F.Lm
Pla_HDBR12330713_AAACCCACAGGCTACC       HBC.Lm
Pla_HDBR12330713_AAACCCACATCGTCCT         F.Lm
Pla_HDBR12330713_AAACCCAGTACCGCGT       HBC.Lm
                                       ...
Pla_HDBR13661572_TTTGTTGAGGTTCATC       HBC.Lm
Pla_HDBR13661572_TTTGTTGCAAATTAGG    Endo_f.Lm
Pla_HDBR13661572_TTTGTTGCAATAGGGC         F.Lm
Pla_HDBR13661572_TTTGTTGGTGCTTATG    Endo_f.Lm
Pla_HDBR13661572_TTTGTTGGTGGTAACG     PAMM1.Lm
Name: cell_type, Length: 17778, dtype: string

In [77]:
cellphoneDB_adata

AnnData object with n_obs × n_vars = 17778 × 36601
    obs: 'sample', 'stage', 'hpi', 'infection', 'percent_mito', 'n_counts', 'sample_barcode', 'assignment_SoC', 'donor_id', 'scrublet_score', 'scrublet_cluster_score', 'zscore', 'bh_pval', 'bonf_pval', 'S_score', 'G2M_score', 'phase', 'n_genes_by_counts', 'total_counts', 'total_counts_hs', 'pct_counts_hs', 'total_counts_tg', 'pct_counts_tg', 'Tg_infected', 'n_genes', '_scvi_batch', '_scvi_labels', '_scvi_local_l_mean', '_scvi_local_l_var', 'leiden_scvi', 'celltype_predictions', 'probabilities', 'scrublet_doublet', 'cell_type_2022', 'cell_type', 'souporcell_MFgenotype', 'MFgenotype', 'cell_type_broad', 'umap_density_Tg_infected', 'stage_perInfection', 'celltype-Stage', 'Tg_intracellular', 'celltype-Intracellular', 'Dev_Stage'
    var: 'gene_ids', 'feature_types', 'mean-0', 'std-0', 'mean-1', 'std-1', 'mean-2', 'std-2', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'Dev_Stage_colors', 'MFgenotype_colors', '_scvi', 'cell_type_2022_colors', 'cell_type_broad_colors', 'cell_type_colors', 'celltype_predictions_colors', 'donor_id_colors', 'hpi_colors', 'hvg', 'infection_colors', 'leiden', 'neighbors', 'sample_colors', 'scrublet_doublet_colors', 'umap', 'umap_density_Tg_infected_params'
    obsm: 'X_scVI_n_latent_20', 'X_scVI_n_latent_30', 'X_scVI_n_latent_40', 'X_umap', '_scvi_extra_categoricals'
    layers: 'raw_counts'
    obsp: 'connectivities', 'distances'

In [78]:
sc.pp.normalize_per_cell(cellphoneDB_adata)
sc.pp.log1p(cellphoneDB_adata)                                                                                                            
# sc.pp.scale(adata, max_value=10)

/opt/conda/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2487: FutureWarning: The `inplace` parameter in pandas.Categorical.remove_unused_categories is deprecated and will be removed in a future version.
  res = method(*args, **kwargs)

### The anndata object contains counts that have been normalized (per cell) and log-transformed, therefore save this as below

In [79]:
# counts input files 
cellphoneDB_adata.write('../data/listeria_inf_normlogTransformed_24h.h5ad')

... storing 'cell_type' as categorical

In [80]:
#cellphoneDB_adata=sc.read('../data/listeria_inf_normlogTransformed.h5ad')
#df_meta= pd.read_csv('../data/listeria_inf_meta.tsv', sep = '\t', index_col=0)

In [81]:
# meta file
df_meta = pd.DataFrame(data={'Cell':list(cellphoneDB_adata.obs.index),
                             'cell_type':[ str(i) for i in cellphoneDB_adata.obs['cell_type']] })
df_meta.set_index('Cell', inplace=True)
df_meta.to_csv('../data/listeria_inf_meta_24h.tsv', sep = '\t')

In [82]:
df_meta

                                   cell_type
Cell
Pla_HDBR12330713_AAACCCAAGTAGAGTT     HBC.Lm
Pla_HDBR12330713_AAACCCACAATTCTCT       F.Lm
Pla_HDBR12330713_AAACCCACAGGCTACC     HBC.Lm
Pla_HDBR12330713_AAACCCACATCGTCCT       F.Lm
Pla_HDBR12330713_AAACCCAGTACCGCGT     HBC.Lm
...                                      ...
Pla_HDBR13661572_TTTGTTGAGGTTCATC     HBC.Lm
Pla_HDBR13661572_TTTGTTGCAAATTAGG  Endo_f.Lm
Pla_HDBR13661572_TTTGTTGCAATAGGGC       F.Lm
Pla_HDBR13661572_TTTGTTGGTGCTTATG  Endo_f.Lm
Pla_HDBR13661572_TTTGTTGGTGGTAACG   PAMM1.Lm

[17778 rows x 1 columns]

In [142]:
set(list(df_meta['cell_type']))

{'EVT_1.Lm',
 'EVT_2.Lm',
 'Endo_f.Lm',
 'F.Lm',
 'F_p.Lm',
 'F_sm.Lm',
 'HBC.Lm',
 'HBC_p.Lm',
 'PAMM1.Lm',
 'PV.Lm',
 'VCT.Lm',
 'VCT_CCC.Lm',
 'VCT_fusing.Lm',
 'VCT_p.Lm',
 'iEVT.Lm'}

### (2) Do DEGs individually from precalculated DEGs files

In [83]:
# PATH to immune cells DGE tables
path='../../diffGeneExpression/macrophages/results/SC_limma_Immune_LIS_24h/'

### HBC

In [84]:
HBDEG = pd.read_csv(path+'/1_DEGs_SC_LIS_24h_HBC.tsv', header=0, index_col=0, sep='\t')

In [85]:
HBDEG

,logFC,logCPM,F,PValue,bonferroni,p_val_adj
STC1,1.288401,6.197037,242.503878,3.226768e-13,2.358122e-09,2.358122e-09
IL1RN,1.022193,7.355690,222.829592,7.465613e-13,5.455870e-09,2.727935e-09
IGFBP4,-0.627356,6.728119,177.960289,6.730971e-12,4.918994e-08,1.639665e-08
ATP13A3,0.468337,7.538326,159.872988,1.887261e-11,1.379211e-07,3.448026e-08
FCGRT,-0.369558,9.378415,151.271960,3.197164e-11,2.336487e-07,4.672975e-08
...,...,...,...,...,...,...
STK17B,-0.000118,6.717451,0.000005,9.982881e-01,1.000000e+00,9.986069e-01
FBXW4,0.000130,5.069345,0.000005,9.982220e-01,1.000000e+00,9.986069e-01
THUMPD3,-0.000173,4.767530,0.000004,9.983336e-01,1.000000e+00,9.986069e-01
ATXN1,0.000060,8.172113,0.000003,9.986977e-01,1.000000e+00,9.987206e-01
TSEN34,0.000099,5.062587,0.000003,9.987206e-01,1.000000e+00,9.987206e-01

In [86]:
HBDEG_up= recoverDEGs(HBDEG, infection='Lm', celltype='HBC', direction='up')
HBDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
STC1,1.288401,6.197037,242.503878,3.226768e-13,2.358122e-09,2.358122e-09,HBC,HBC.Lm,STC1
IL1RN,1.022193,7.355690,222.829592,7.465613e-13,5.455870e-09,2.727935e-09,HBC,HBC.Lm,IL1RN
ATP13A3,0.468337,7.538326,159.872988,1.887261e-11,1.379211e-07,3.448026e-08,HBC,HBC.Lm,ATP13A3
SAMSN1,0.451065,8.824758,130.151077,1.316877e-10,9.623734e-07,1.374819e-07,HBC,HBC.Lm,SAMSN1
AL360227.1,0.779019,4.882505,126.551758,1.709469e-10,1.249280e-06,1.388089e-07,HBC,HBC.Lm,AL360227.1

In [87]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in HBDEG_up.cluster])
HBDEG_up = HBDEG_up[ idx ]

In [89]:
# 1st column = cluster; 2nd column = gene 
cncol = HBDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
HBDEG_up= HBDEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(HBDEG_up).to_csv('../data/listeria_inf_HBC_DEGsup.tsv', sep='\t', index=False)

In [90]:
#list(HBDEG_up.gene)

In [91]:
#HBDEG_up=pd.read_table('../data/listeria_inf_HBC_DEGsup.tsv')
#HBDEG_up.loc[['VEGFA']]
HBDEG_up.loc[HBDEG_up['gene'] == 'VEGFA']

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
VEGFA,HBC.Lm,VEGFA,0.77482,6.253933,90.455904,3.572045e-09,0.000026,7.458431e-07,HBC

### PAMM1

In [92]:
PAMM1DEG = pd.read_csv(path+'/2_DEGs_SC_LIS_24h_PAMM1.tsv', header=0, index_col=0, sep='\t')

In [93]:
PAMM1DEG_up= recoverDEGs(PAMM1DEG, infection='Lm', celltype='PAMM1', direction='up')
PAMM1DEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
C15orf48,1.144871,9.545963,88.965254,7.574555e-10,0.000005,0.000005,PAMM1,PAMM1.Lm,C15orf48
STC1,1.372473,5.604870,80.251079,2.121684e-09,0.000013,0.000006,PAMM1,PAMM1.Lm,STC1
C1orf56,1.185322,5.357605,62.887467,2.195464e-08,0.000134,0.000045,PAMM1,PAMM1.Lm,C1orf56
TIMP1,0.744604,10.769514,57.788443,4.768015e-08,0.000290,0.000058,PAMM1,PAMM1.Lm,TIMP1
MARCKS,0.597890,9.892981,58.744905,4.107608e-08,0.000250,0.000058,PAMM1,PAMM1.Lm,MARCKS

In [94]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in PAMM1DEG_up.cluster])
PAMM1DEG_up = PAMM1DEG_up[ idx ]

In [95]:
# 1st column = cluster; 2nd column = gene 
cncol = PAMM1DEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
PAMM1DEG_up= PAMM1DEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(PAMM1DEG_up).to_csv('../data/listeria_inf_PAMM1_DEGsup.tsv', sep='\t', index=False)

In [96]:
PAMM1DEG_up.head(5)

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
C15orf48,PAMM1.Lm,C15orf48,1.144871,9.545963,88.965254,7.574555e-10,0.000005,0.000005,PAMM1
STC1,PAMM1.Lm,STC1,1.372473,5.604870,80.251079,2.121684e-09,0.000013,0.000006,PAMM1
C1orf56,PAMM1.Lm,C1orf56,1.185322,5.357605,62.887467,2.195464e-08,0.000134,0.000045,PAMM1
TIMP1,PAMM1.Lm,TIMP1,0.744604,10.769514,57.788443,4.768015e-08,0.000290,0.000058,PAMM1
MARCKS,PAMM1.Lm,MARCKS,0.597890,9.892981,58.744905,4.107608e-08,0.000250,0.000058,PAMM1

In [143]:
# PATH to FibroEndo cells DGE tables
path='../../diffGeneExpression/fibroEndo/results/SC_limma_fibroEndo_LIS_24h/'

### F

In [144]:
FDEG = pd.read_csv(path+'/1_DEGs_SC_LIS_24h_F.tsv', header=0, index_col=0, sep='\t')

In [145]:
FDEG_up= recoverDEGs(FDEG, infection='Lm', celltype='F', direction='up')
FDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
SLC30A4,0.773521,5.872970,121.331122,5.458952e-10,0.000004,0.000001,F,F.Lm,SLC30A4
ATP10B,1.159572,4.096377,112.813973,1.026411e-09,0.000008,0.000002,F,F.Lm,ATP10B
WDR45B,0.466109,6.572808,99.179367,3.086850e-09,0.000023,0.000002,F,F.Lm,WDR45B
MARCKS,0.681913,9.354571,99.287132,3.058607e-09,0.000023,0.000002,F,F.Lm,MARCKS
LINC02326,0.698494,6.232710,96.452308,3.906280e-09,0.000030,0.000002,F,F.Lm,LINC02326

In [146]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in FDEG_up.cluster])
FDEG_up = FDEG_up[ idx ]

In [147]:
# 1st column = cluster; 2nd column = gene 
cncol = FDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
FDEG_up= FDEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(FDEG_up).to_csv('../data/listeria_inf_F_DEGsup.tsv', sep='\t', index=False)

In [148]:
FDEG_up.head()

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
SLC30A4,F.Lm,SLC30A4,0.773521,5.872970,121.331122,5.458952e-10,0.000004,0.000001,F
ATP10B,F.Lm,ATP10B,1.159572,4.096377,112.813973,1.026411e-09,0.000008,0.000002,F
WDR45B,F.Lm,WDR45B,0.466109,6.572808,99.179367,3.086850e-09,0.000023,0.000002,F
MARCKS,F.Lm,MARCKS,0.681913,9.354571,99.287132,3.058607e-09,0.000023,0.000002,F
LINC02326,F.Lm,LINC02326,0.698494,6.232710,96.452308,3.906280e-09,0.000030,0.000002,F

In [149]:
FDEG_up.loc[['THBS2']]

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
THBS2,F.Lm,THBS2,0.783961,5.117159,21.837357,0.000143,1.0,0.001318,F

### PV

In [150]:
PVDEG = pd.read_csv(path+'/2_DEGs_SC_LIS_24h_PV.tsv', header=0, index_col=0, sep='\t')

In [151]:
PVDEG_up= recoverDEGs(PVDEG, infection='Lm', celltype='PV', direction='up')
PVDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
IL1B,1.441441,5.748745,83.425492,2.861042e-09,0.000021,0.000021,PV,PV.Lm,IL1B
AL133453.1,0.628851,6.338373,70.006608,1.441496e-08,0.000108,0.000036,PV,PV.Lm,AL133453.1
LINC02326,0.805504,6.203114,71.988762,1.119157e-08,0.000084,0.000036,PV,PV.Lm,LINC02326
STC1,1.174349,9.604055,65.198570,2.726236e-08,0.000205,0.000041,PV,PV.Lm,STC1
AC009554.1,0.919839,5.432419,66.342901,2.335296e-08,0.000175,0.000041,PV,PV.Lm,AC009554.1

In [152]:
PVDEG_up

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
IL1B,1.441441,5.748745,83.425492,2.861042e-09,0.000021,0.000021,PV,PV.Lm,IL1B
AL133453.1,0.628851,6.338373,70.006608,1.441496e-08,0.000108,0.000036,PV,PV.Lm,AL133453.1
LINC02326,0.805504,6.203114,71.988762,1.119157e-08,0.000084,0.000036,PV,PV.Lm,LINC02326
STC1,1.174349,9.604055,65.198570,2.726236e-08,0.000205,0.000041,PV,PV.Lm,STC1
AC009554.1,0.919839,5.432419,66.342901,2.335296e-08,0.000175,0.000041,PV,PV.Lm,AC009554.1
...,...,...,...,...,...,...,...,...,...
MYO9B,0.275462,6.544115,9.349547,5.418162e-03,1.000000,0.047871,PV,PV.Lm,MYO9B
LGALS1,0.148322,11.244907,9.338860,5.440826e-03,1.000000,0.048015,PV,PV.Lm,LGALS1
AKAP13,0.219309,8.574686,9.308130,5.506573e-03,1.000000,0.048424,PV,PV.Lm,AKAP13
PMM2,0.290057,6.346882,9.249752,5.633888e-03,1.000000,0.049256,PV,PV.Lm,PMM2
FUT11,0.247233,6.037282,9.224587,5.689764e-03,1.000000,0.049628,PV,PV.Lm,FUT11

In [153]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in PVDEG_up.cluster])
PVDEG_up = PVDEG_up[ idx ]

In [154]:
# 1st column = cluster; 2nd column = gene 
cncol = PVDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
PVDEG_up= PVDEG_up[ ['cluster', 'gene']+cncol ]

pd.DataFrame(PVDEG_up).to_csv('../data/listeria_inf_PV_DEGsup.tsv', sep='\t', index=False)

In [155]:
PVDEG_up.head()

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
IL1B,PV.Lm,IL1B,1.441441,5.748745,83.425492,2.861042e-09,0.000021,0.000021,PV
AL133453.1,PV.Lm,AL133453.1,0.628851,6.338373,70.006608,1.441496e-08,0.000108,0.000036,PV
LINC02326,PV.Lm,LINC02326,0.805504,6.203114,71.988762,1.119157e-08,0.000084,0.000036,PV
STC1,PV.Lm,STC1,1.174349,9.604055,65.198570,2.726236e-08,0.000205,0.000041,PV
AC009554.1,PV.Lm,AC009554.1,0.919839,5.432419,66.342901,2.335296e-08,0.000175,0.000041,PV

### Endo_f

In [156]:
EndoDEG = pd.read_csv(path+'/3_DEGs_SC_LIS_24h_Endof.tsv', header=0, index_col=0, sep='\t')

In [157]:
EndoDEG_up= recoverDEGs(EndoDEG, infection='Lm', celltype='Endo_f', direction='up')
EndoDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
C15orf48,0.954024,4.448099,126.433440,1.752048e-11,1.298793e-07,1.290975e-07,Endo_f,Endo_f.Lm,C15orf48
IL1B,1.031443,5.523735,98.954441,2.370360e-10,1.757148e-06,4.392869e-07,Endo_f,Endo_f.Lm,IL1B
C1orf56,0.969427,5.265645,101.557146,1.808770e-10,1.340841e-06,4.392869e-07,Endo_f,Endo_f.Lm,C1orf56
DTWD2,1.169978,4.599164,95.351859,3.479421e-10,2.579295e-06,5.158590e-07,Endo_f,Endo_f.Lm,DTWD2
CXCL5,0.943957,5.881886,89.663507,6.534115e-10,4.843740e-06,8.072899e-07,Endo_f,Endo_f.Lm,CXCL5

In [158]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in EndoDEG_up.cluster])
EndoDEG_up = EndoDEG_up[ idx ]

In [159]:
# 1st column = cluster; 2nd column = gene 
cncol = EndoDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
EndoDEG_up= EndoDEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(EndoDEG_up).to_csv('../data/listeria_inf_Endof_DEGsup.tsv', sep='\t', index=False)

In [160]:
EndoDEG_up.head()

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
C15orf48,Endo_f.Lm,C15orf48,0.954024,4.448099,126.433440,1.752048e-11,1.298793e-07,1.290975e-07,Endo_f
IL1B,Endo_f.Lm,IL1B,1.031443,5.523735,98.954441,2.370360e-10,1.757148e-06,4.392869e-07,Endo_f
C1orf56,Endo_f.Lm,C1orf56,0.969427,5.265645,101.557146,1.808770e-10,1.340841e-06,4.392869e-07,Endo_f
DTWD2,Endo_f.Lm,DTWD2,1.169978,4.599164,95.351859,3.479421e-10,2.579295e-06,5.158590e-07,Endo_f
CXCL5,Endo_f.Lm,CXCL5,0.943957,5.881886,89.663507,6.534115e-10,4.843740e-06,8.072899e-07,Endo_f

In [115]:
# PATH to Trophoblast cells DGE tables
path='../../diffGeneExpression/trophoblast/results/SC_limma_Trophoblast_LIS_24h'

### VCT_fusing

In [116]:
VCTfDEG = pd.read_csv(path+'/1_DEGs_SC_LIS_24h_VCT_fusing.tsv', header=0, index_col=0, sep='\t')

In [117]:
VCTfDEG_up= recoverDEGs(VCTfDEG, infection='Lm', celltype='VCT_fusing', direction='up')
VCTfDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
TIMP1,0.680611,8.260483,79.159917,1.465612e-08,0.000111,0.000034,VCT_fusing,VCT_fusing.Lm,TIMP1
IL1B,1.054424,4.226661,75.946173,2.071042e-08,0.000157,0.000034,VCT_fusing,VCT_fusing.Lm,IL1B
CCL20,1.289987,4.382292,75.347699,2.211625e-08,0.000168,0.000034,VCT_fusing,VCT_fusing.Lm,CCL20
PTGS2,1.212487,3.317895,72.663077,2.984766e-08,0.000227,0.000038,VCT_fusing,VCT_fusing.Lm,PTGS2
LINC02109,1.920732,5.358849,58.137602,1.789002e-07,0.001358,0.000194,VCT_fusing,VCT_fusing.Lm,LINC02109

In [118]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in VCTfDEG_up.cluster])
VCTfVCTfDEG_upDEG = VCTfDEG_up[ idx ]

In [119]:
# 1st column = cluster; 2nd column = gene 
cncol = VCTfDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
VCTfDEG_up= VCTfDEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(VCTfDEG_up).to_csv('../data/listeria_inf_VCTfusing_DEGsup.tsv', sep='\t', index=False)

In [120]:
VCTfDEG_up.head()

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
TIMP1,VCT_fusing.Lm,TIMP1,0.680611,8.260483,79.159917,1.465612e-08,0.000111,0.000034,VCT_fusing
IL1B,VCT_fusing.Lm,IL1B,1.054424,4.226661,75.946173,2.071042e-08,0.000157,0.000034,VCT_fusing
CCL20,VCT_fusing.Lm,CCL20,1.289987,4.382292,75.347699,2.211625e-08,0.000168,0.000034,VCT_fusing
PTGS2,VCT_fusing.Lm,PTGS2,1.212487,3.317895,72.663077,2.984766e-08,0.000227,0.000038,VCT_fusing
LINC02109,VCT_fusing.Lm,LINC02109,1.920732,5.358849,58.137602,1.789002e-07,0.001358,0.000194,VCT_fusing

In [121]:
VCTfDEG_up.loc[['SPP1']]

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
SPP1,VCT_fusing.Lm,SPP1,0.662044,7.817243,56.992413,2.089290e-07,0.001586,0.000198,VCT_fusing

### VCT

In [124]:
VCTDEG = pd.read_csv(path+'/2_DEGs_SC_LIS_24h_VCT.tsv', header=0, index_col=0, sep='\t')

In [125]:
VCTDEG_up= recoverDEGs(VCTDEG, infection='Lm', celltype='VCT', direction='up')
VCTDEG_up.head(5)

,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type,cluster,gene
TIMP1,0.790908,8.111007,161.926302,1.839387e-12,1.749257e-08,1.749257e-08,VCT,VCT.Lm,TIMP1
CXCL8,0.717749,7.067350,132.519030,1.602635e-11,1.524106e-07,7.620529e-08,VCT,VCT.Lm,CXCL8
CLIP4,0.551446,6.074261,96.669251,4.221855e-10,4.014984e-06,5.735692e-07,VCT,VCT.Lm,CLIP4
IL1B,1.245488,4.258540,99.110268,3.281763e-10,3.120956e-06,5.735692e-07,VCT,VCT.Lm,IL1B
ADAM12,1.024389,7.483833,92.547554,6.536630e-10,6.216335e-06,6.907039e-07,VCT,VCT.Lm,ADAM12

In [126]:
# make sure DEGs only includes samples in meta
cl2include = set(cellphoneDB_adata.obs.cell_type.tolist())
idx = np.array([i in cl2include for i in VCTDEG_up.cluster])
VCTDEG_up = VCTDEG_up[ idx ]

In [127]:
# 1st column = cluster; 2nd column = gene 
cncol = VCTDEG_up.columns.tolist()
cncol = [item for item in cncol if item not in ['cluster', 'gene'] ]
VCTDEG_up= VCTDEG_up[ ['cluster', 'gene']+cncol ]
pd.DataFrame(VCTDEG_up).to_csv('../data/listeria_inf_VCT_DEGsup.tsv', sep='\t', index=False)

In [128]:
VCTDEG_up.head()

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
TIMP1,VCT.Lm,TIMP1,0.790908,8.111007,161.926302,1.839387e-12,1.749257e-08,1.749257e-08,VCT
CXCL8,VCT.Lm,CXCL8,0.717749,7.067350,132.519030,1.602635e-11,1.524106e-07,7.620529e-08,VCT
CLIP4,VCT.Lm,CLIP4,0.551446,6.074261,96.669251,4.221855e-10,4.014984e-06,5.735692e-07,VCT
IL1B,VCT.Lm,IL1B,1.245488,4.258540,99.110268,3.281763e-10,3.120956e-06,5.735692e-07,VCT
ADAM12,VCT.Lm,ADAM12,1.024389,7.483833,92.547554,6.536630e-10,6.216335e-06,6.907039e-07,VCT

In [129]:
VCTDEG_up.loc[['SPP1']]

,cluster,gene,logFC,logCPM,F,PValue,bonferroni,p_val_adj,cell_type
SPP1,VCT.Lm,SPP1,0.683136,7.794127,65.946544,1.703181e-08,0.000162,0.000004,VCT

### (3) Run cellphoneDB

source activate cpdb

bash run_cellphoneDB.sh